using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Markup;
using BendDataBase.WiCAM.Pn4000.pn4.Sym3D.BendSimulation.PnConfig.Tools.Profiles;
using Telerik.Windows.Controls;
using Telerik.Windows.Controls.Data.PropertyGrid;
using Telerik.Windows.Controls.Primitives;

namespace WiCAM.Pn4000.PN3D.Popup.UI.Views;

public partial class EditScreenView : UserControl, IComponentConnector
{
	private DataTemplate _geometryFileTemplate;

	private DataTemplate _toolItemViewModelBaseTemplate;

	public EditScreenView()
	{
		this.InitializeComponent();
	}

	private void PropertyGrid_AutoGeneratingPropertyDefinition(object sender, AutoGeneratingPropertyDefinitionEventArgs e)
	{
		string autoGeneratedPath = e.PropertyDefinition.AutoGeneratedPath;
		string text = "";
		string upperLower = "";
		Type type = (sender as RadPropertyGrid).Item.GetType();
		if (type == typeof(PunchPartViewModel))
		{
			text = "l_popup.PunchesView.";
		}
		else if (type == typeof(PunchProfileViewModel))
		{
			text = "l_popup.PunchesView.";
			upperLower = "Upper";
		}
		else if (type == typeof(DiePartViewModel))
		{
			text = "l_popup.DiesView.";
		}
		else if (type == typeof(DieProfileViewModel))
		{
			text = "l_popup.DiesView.";
			upperLower = "Lower";
		}
		else if (type == typeof(PreferredProfileViewModel))
		{
			text = "l_popup.PreferredToolsView.";
		}
		else if (type == typeof(PunchGroupViewModel))
		{
			text = "l_popup.GroupsView.";
		}
		else if (type == typeof(DieGroupViewModel))
		{
			text = "l_popup.GroupsView.";
		}
		else if (type == typeof(SensorDiskViewModel))
		{
			text = "l_popup.PunchesView.";
		}
		else if (type == typeof(HemProfileViewModel))
		{
			text = "l_popup.DieHemView.";
		}
		else if (type == typeof(HemPartViewModel))
		{
			text = "l_popup.DieHemView.";
		}
		else if (type == typeof(AdapterProfileViewModel))
		{
			text = "l_popup.AdapterView.";
		}
		else if (type == typeof(AdapterPartViewModel))
		{
			text = "l_popup.AdapterView.";
		}
		else if (type == typeof(HolderProfileViewModel))
		{
			text = "l_popup.HolderView.";
		}
		else if (type == typeof(HolderPartViewModel))
		{
			text = "l_popup.HolderView.";
		}
		if (autoGeneratedPath == "GeometryFile")
		{
			this.CreateGeometryTemplate(autoGeneratedPath);
			e.PropertyDefinition.EditorTemplate = this._geometryFileTemplate;
		}
		else if (e.PropertyDefinition.SourceProperty.PropertyType.BaseType == typeof(ToolItemViewModelBase))
		{
			this.CreateToolItemViewModelBaseTemplate(autoGeneratedPath, upperLower);
			e.PropertyDefinition.EditorTemplate = this._toolItemViewModelBaseTemplate;
		}
		e.PropertyDefinition.DisplayName = (string)Application.Current.TryFindResource(text + autoGeneratedPath);
		string.IsNullOrEmpty(e.PropertyDefinition.DisplayName);
		e.PropertyDefinition.Description = (string)Application.Current.TryFindResource(text + autoGeneratedPath + ".Desc");
		e.PropertyDefinition.GroupName = (string)Application.Current.TryFindResource(text + autoGeneratedPath + ".Grp");
	}

	private void CreateGeometryTemplate(string propertyName)
	{
		this._geometryFileTemplate = new DataTemplate
		{
			DataType = typeof(RadAutoCompleteBox)
		};
		if (!this._geometryFileTemplate.IsSealed)
		{
			FrameworkElementFactory frameworkElementFactory = new FrameworkElementFactory(typeof(RadAutoCompleteBox));
			UserControl userControl = EditScreenView.FindParent<UserControl>(this);
			object value = userControl.DataContext.GetType().GetProperty(propertyName + "s").GetValue(userControl.DataContext);
			frameworkElementFactory.SetBinding(RadAutoCompleteBox.ItemsSourceProperty, new Binding
			{
				Source = value
			});
			frameworkElementFactory.SetBinding(RadAutoCompleteBox.SelectedItemProperty, new Binding(propertyName));
			frameworkElementFactory.SetValue(RadAutoCompleteBox.DisplayMemberPathProperty, "Name");
			frameworkElementFactory.SetValue(RadAutoCompleteBox.WatermarkContentProperty, "Type here");
			frameworkElementFactory.SetValue(RadAutoCompleteBox.TextSearchModeProperty, TextSearchMode.Contains);
			frameworkElementFactory.SetValue(RadAutoCompleteBox.AutoCompleteModeProperty, AutoCompleteMode.SuggestAppend);
			frameworkElementFactory.SetValue(RadAutoCompleteBox.NoResultsContentProperty, "No results found");
			frameworkElementFactory.SetValue(RadAutoCompleteBox.SelectionModeProperty, AutoCompleteSelectionMode.Single);
			this._geometryFileTemplate.VisualTree = frameworkElementFactory;
			this._geometryFileTemplate.Seal();
		}
	}

	private void CreateToolItemViewModelBaseTemplate(string propertyName, string upperLower)
	{
		this._toolItemViewModelBaseTemplate = new DataTemplate
		{
			DataType = typeof(ComboBox)
		};
		if (!this._toolItemViewModelBaseTemplate.IsSealed)
		{
			FrameworkElementFactory frameworkElementFactory = new FrameworkElementFactory(typeof(RadComboBox));
			UserControl userControl = EditScreenView.FindParent<UserControl>(this);
			object value = userControl.DataContext.GetType().GetProperty("ToolConfigModel").GetValue(userControl.DataContext);
			bool flag = propertyName == "Adapter" || propertyName == "Holder";
			object source = ((!(propertyName == "FrontHemPart") && !(propertyName == "BackHemPart")) ? (flag ? value.GetType().GetProperty(upperLower + propertyName + "Profiles").GetValue(value) : value.GetType().GetProperty(propertyName + "s").GetValue(value)) : ((propertyName == "FrontHemPart") ? value.GetType().GetProperty("FrontHemProfiles").GetValue(value) : value.GetType().GetProperty("BackHemProfiles").GetValue(value)));
			frameworkElementFactory.SetBinding(ItemsControl.ItemsSourceProperty, new Binding
			{
				Source = source
			});
			frameworkElementFactory.SetBinding(Selector.SelectedItemProperty, new Binding(propertyName));
			frameworkElementFactory.SetValue(ItemsControl.DisplayMemberPathProperty, "Name");
			this._toolItemViewModelBaseTemplate.VisualTree = frameworkElementFactory;
			this._toolItemViewModelBaseTemplate.Seal();
		}
	}

	public static T FindParent<T>(DependencyObject child) where T : DependencyObject
	{
		DependencyObject dependencyObject = child.GetParents().FirstOrDefault();
		if (dependencyObject == null)
		{
			return null;
		}
		if (dependencyObject is T result)
		{
			return result;
		}
		return EditScreenView.FindParent<T>(dependencyObject);
	}
}
