using System;
using System.Windows;
using Microsoft.Extensions.DependencyInjection;
using WiCAM.Pn4000.BendModel.Base;
using WiCAM.Pn4000.Contracts.Doc3d;
using WiCAM.Pn4000.Contracts.EventTokens;
using WiCAM.Pn4000.Contracts.Extensions;
using WiCAM.Pn4000.Contracts.ManualCameraStateView;
using WiCAM.Pn4000.Contracts.PipeService;
using WiCAM.Pn4000.Contracts.PnCommands;
using WiCAM.Pn4000.Contracts.Telemetry;
using WiCAM.Pn4000.Contracts.Tools;
using WiCAM.Pn4000.GuiContracts;
using WiCAM.Pn4000.GuiContracts.EventArgs;
using WiCAM.Pn4000.GuiContracts.PnStatusBar;
using WiCAM.Pn4000.GuiContracts.Popups;
using WiCAM.Pn4000.GuiContracts.Tools;
using WiCAM.Pn4000.GuiWpf.Assembly;
using WiCAM.Pn4000.GuiWpf.EventTokens;
using WiCAM.Pn4000.GuiWpf.F7;
using WiCAM.Pn4000.GuiWpf.GeneralSubWindow;
using WiCAM.Pn4000.GuiWpf.GeneralSubWindow.Settings;
using WiCAM.Pn4000.GuiWpf.GeneralUI.Docking;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Bend;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Bend.CalculationInfo;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Bend.DocInfo;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Bend.Machine;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Bend.Material;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Bend.Model;
using WiCAM.Pn4000.GuiWpf.GeneralUI.PnStatusBar.Fortran;
using WiCAM.Pn4000.GuiWpf.GeneralUI.Popups;
using WiCAM.Pn4000.GuiWpf.L26;
using WiCAM.Pn4000.GuiWpf.PnCommand;
using WiCAM.Pn4000.GuiWpf.Services;
using WiCAM.Pn4000.GuiWpf.TabBend;
using WiCAM.Pn4000.GuiWpf.TabBend.BendSequenceList;
using WiCAM.Pn4000.GuiWpf.TabBend.BendSequenceList.BendContext;
using WiCAM.Pn4000.GuiWpf.TabBend.Developer;
using WiCAM.Pn4000.GuiWpf.TabBend.EditBendOrderPopup;
using WiCAM.Pn4000.GuiWpf.TabBend.EditFingers;
using WiCAM.Pn4000.GuiWpf.TabBend.EditFingers.Interfaces;
using WiCAM.Pn4000.GuiWpf.TabBend.EditLcb;
using WiCAM.Pn4000.GuiWpf.TabBend.EditLiftingAids;
using WiCAM.Pn4000.GuiWpf.TabBend.EditTools;
using WiCAM.Pn4000.GuiWpf.TabBend.EditTools.Interafces;
using WiCAM.Pn4000.GuiWpf.TabBend.OpacityControl;
using WiCAM.Pn4000.GuiWpf.TabBend.OrderBillboards;
using WiCAM.Pn4000.GuiWpf.TabBend.PPaperSettings;
using WiCAM.Pn4000.GuiWpf.TabBend.SequenceList;
using WiCAM.Pn4000.GuiWpf.TabBend.SnapPointSettings;
using WiCAM.Pn4000.GuiWpf.TabUnfold;
using WiCAM.Pn4000.GuiWpf.TabViewer3D;
using WiCAM.Pn4000.GuiWpf.Ui3D;
using WiCAM.Pn4000.GuiWpf.Ui3D.DocManagement;
using WiCAM.Pn4000.GuiWpf.Ui3D.Legend;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.SubBendTable;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.SubTabs;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools.Importers;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools.Importers.Utility;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools.ToolViewModels;
using WiCAM.Pn4000.GuiWpf.UiBendMachine;
using WiCAM.Pn4000.GuiWpf.UiBendMachine.SelectMachine;
using WiCAM.Pn4000.PN3D.BendSimulation.Configuration;
using WiCAM.Pn4000.PN3D.BendSimulation.PP;
using WiCAM.Pn4000.PN3D.Popup.Information;
using WiCAM.Pn4000.PN3D.Popup.Model;
using WiCAM.Pn4000.PN3D.Popup.UI.ViewModels;
using WiCAM.Pn4000.PN3D.Popup.View;
using WiCAM.Pn4000.PN3D.Popup.ViewModel;
using WiCAM.Pn4000.ScreenD3D.Controls;
using WiCAM.Pn4000.ToolCalculationGuiWpf;
using WiCAM.Pn4000.ToolCalculationGuiWpf.EditTools.SubViews;
using WiCAM.Pn4000.WpfControls;
using WiCAM.Pn4000.WpfDSTV.Extensions;

namespace WiCAM.Pn4000.GuiWpf;

public static class DependencyInjection
{
	public static void AddGuiWpf(this IServiceCollection service)
	{
		service.AddSingleton<IStyleProvider, StyleProvider>();
		service.AddSingleton<IModelStyleProvider, ModelStyleProvider>();
		service.AddSingleton<IPnCommandBasics, PnCommandBasics>();
		service.AddSingletonIntercepted<IPnCommandsBend, PnCommandsBend>();
		service.AddSingletonIntercepted<IPnCommandsUnfold, PnCommandsUnfold>();
		service.AddSingletonIntercepted<IPnCommandsScreen, PnCommandsScreen>();
		service.AddSingletonIntercepted<IPnCommandsOther, PnCommandsOther>();
		service.AddScoped<IBendSequenceSortViewModel, BendSequenceSortViewModel>();
		service.AddSingleton<IBlockBendToken, BlockBendToken>();
		service.AddSingleton<IWorkStatusToken, WorkStatusToken>();
		service.AddSingleton<IScreen3DMain, Screen3DMain>();
		service.AddScoped<IScreen3DDoc, Screen3DDoc>();
		service.AddSingleton<IUiDocManager, UiDocManager>();
		service.AddSingleton<IDrawToolProfiles, DrawToolProfiles>();
		service.AddSingleton<IUiBendMachineService, UiBendMachineService>();
		service.AddSingleton<ToolCalculationMode>();
		service.AddSingleton<IPnStatusBarHelper, PnStatusBarHelper>();
		service.AddSingleton<IPKernelStatusBarModel, PKernelStatusBarModel>();
		service.AddSingleton<IPKernelStatusBarViewModel, PKernelStatusBarViewModel>();
		service.AddSingleton<IPnStatusBarPKernelSlot0Control, PnStatusBarPKernelSlot0Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot1Control, PnStatusBarPKernelSlot1Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot2Control, PnStatusBarPKernelSlot2Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot3Control, PnStatusBarPKernelSlot3Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot4Control, PnStatusBarPKernelSlot4Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot5Control, PnStatusBarPKernelSlot5Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot6Control, PnStatusBarPKernelSlot6Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot7Control, PnStatusBarPKernelSlot7Control>();
		service.AddSingleton<IPnStatusBarPKernelSlot8Control, PnStatusBarPKernelSlot8Control>();
		service.AddSingleton<IStatus3dDefault, Status3dDefault>();
		service.AddSingleton<IStatus3dDocInfoView, Status3dDocInfoView>();
		service.AddSingleton<IStatus3dDocInfoViewModel, Status3dDocInfoViewModel>();
		service.AddSingleton<IStatus3dMaterialViewModel, Status3dMaterialViewModel>();
		service.AddSingleton<IStatus3dMaterialView, Status3dMaterialView>();
		service.AddSingleton<IStatus3dMachineView, Status3dMachineView>();
		service.AddSingleton<IStatus3dMachineViewModel, Status3dMachineViewModel>();
		service.AddSingleton<IStatus3dModelComponentsView, Status3dModelComponentsView>();
		service.AddSingleton<IStatus3dModelDimensionView, Status3dModelDimensionView>();
		service.AddSingleton<IStatus3dModelTypeView, Status3dModelTypeView>();
		service.AddSingleton<IStatus3dModelInfoViewModel, Status3dModelInfoViewModel>();
		service.AddSingleton<Status3dCalculationInfoViewModel>();
		service.AddSingleton<IMainWindowTaskbarItemInfo, MainWindowTaskbarItemInfo>();
		service.AddSingleton<IStatus3dCalculationInfoView, Status3dCalculationInfoView>();
		service.AddDstvConfig();
		service.AddSingleton<MainWindowViewModel>();
		service.AddSingleton<IDocumentManagerViewModel, DocumentManagerViewModel>();
		service.AddSingleton<IToolSetupMemory, ToolSetupMemory>();
		service.AddTransient<PopupMachineConfigModel>();
		service.AddTransient<PopupMachineConfigViewModel>();
		service.AddTransient<MachineConfigurationView>();
		service.AddTransient<IEditOrderViewModel, EditOrderViewModel>();
		service.AddTransient<EditOrderView>();
		service.AddTransient<PopupUnfoldInfoModel>();
		service.AddTransient<PopupUnfoldInfoViewModel>();
		service.AddTransient<PopupUnfoldInfoView>();
		service.AddScoped<IInfoViewModel, InfoViewModel>();
		service.AddTransient<PopupSelectMaterialModel>();
		service.AddTransient<PopupSelectMaterialViewModel>();
		service.AddTransient<PopupSelectMaterialView>();
		service.AddTransient<BendContextViewModel>();
		service.AddSingleton<BendContextView>();
		service.AddTransient<BendContextStepBendViewModel>();
		service.AddSingleton<BendContextStepBendView>();
		service.AddScoped<IUnfoldViewModel, UnfoldViewModel>();
		service.AddScoped<IBendViewModel, BendViewModel>();
		service.AddScoped<IViewer3dViewModel, Viewer3dViewModel>();
		service.AddSingleton<IProfileOpacitySelector, ProfileOpacitySelector>();
		service.AddTransient<OpacityControlViewModel>();
		service.AddTransient<OpacityControlView>();
		service.AddTransient<BendSequenceListView>();
		service.AddScoped<IBendSequenceListViewModel, BendSequenceListViewModel>();
		service.AddScoped<IMachineBasePainter, MachineBasePainter>();
		service.AddScoped<IBendSelection, BendSelection>();
		service.AddScoped<IEditToolsSelection, EditToolsSelection>();
		service.AddScoped<IEditToolsVisualizer, EditToolsVisualizer>();
		service.AddScoped<IEditToolsViewModel, EditToolsViewModel>();
		service.AddSingleton<EditToolsView>();
		service.AddScoped<IEditLiftingAidsViewModel, EditLiftingAidsViewModel>();
		service.AddSingleton<EditLiftingAidsView>();
		service.AddScoped<IEditLcbViewModel, EditLcbViewModel>();
		service.AddSingleton<EditLcbView>();
		service.AddSingleton<ShortcutEditTools>();
		service.AddSingleton<ShortcutTabBend>();
		service.AddScoped<IEditToolsBillboards, EditToolsBillboards>();
		service.AddScoped<IEditBendPositionBillboards, EditBendPositionBillboards>();
		service.AddScoped<IEditFingersVisualizer, EditFingersVisualizer>();
		service.AddScoped<IFingers2DDragVisualizerR, Fingers2DDragVisualizerR>();
		service.AddScoped<IFingers2DDragVisualizerXZ, Fingers2DDragVisualizerXZ>();
		service.AddScoped<IFingers3DDragVisualizerR, Fingers3DDragVisualizerR>();
		service.AddScoped<IFingers3DDragVisualizerXZ, Fingers3DDragVisualizerXZ>();
		service.AddScoped<IEditFingersBillboards, EditFingersBillboards>();
		service.AddScoped<IEditFingersViewModel, EditFingersViewModel>();
		service.AddSingleton<EditFingersView>();
		service.AddScoped<ISnapPointViewModel, SnapPointViewModel>();
		service.AddSingleton<SnapPointView>();
		service.AddSingleton<ToolCalculationOptionView>();
		service.AddScoped<IToolCalculationOptionViewModel, ToolCalculationOptionViewModel>();
		service.AddTransient<IEditToolsExtendPiecesVisualizer, EditToolsExtendPiecesVisualizer>();
		service.AddTransient<IEditToolsAddPieceVisualizer, EditToolsAddPieceVisualizer>();
		service.AddTransient<IEditToolsDragPiecesVisualizer, EditToolsDragPiecesVisualizer>();
		service.AddTransient<IEditToolsDragModelVisualizer, EditToolsDragPiecesVisualizer>();
		service.AddTransient<IModelDragVisualizerX, ModelDragVisualizerX>();
		service.AddScoped<IOrderBillboardsViewModel, OrderBillboardsViewModel>();
		service.AddSingleton<OrderBillboardsView>();
		service.AddTransient<GeometryMeasureToolsViewModel>();
		service.AddTransient<AngleMeasurementViewModel>();
		service.AddTransient<IValidationViewModel, ValidationViewModel>();
		service.AddTransient<F7View>();
		service.AddTransient<F7ViewModel>();
		service.AddTransient<PopupBendParameterModel>();
		service.AddTransient<PopupBendParameterViewModel>();
		service.AddTransient<PopupBendParameterView>();
		service.AddTransient<MachineToolsViewModel>();
		service.AddTransient<UpperToolsViewModel>();
		service.AddTransient<LowerToolsViewModel>();
		service.AddTransient<LowerToolExtensionsViewModel>();
		service.AddTransient<WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools.ToolViewModels.ToolGeneralViewModel>();
		service.AddTransient<LowerAdaptersViewModel>();
		service.AddTransient<UpperAdaptersViewModel>();
		service.AddTransient<DieHemViewModel>();
		service.AddTransient<WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools.ToolViewModels.ToolGroupsViewModel>();
		service.AddTransient<PreferredProfilesViewModel>();
		service.AddTransient<AssignAliasViewModel>();
		service.AddTransient<FingerViewModel>();
		service.AddTransient<UpperAdapterViewModel>();
		service.AddTransient<LowerAdapterViewModel>();
		service.AddTransient<UpperHolderViewModel>();
		service.AddTransient<LowerHolderViewModel>();
		service.AddTransient<ClampingSystemViewModel>();
		service.AddTransient<MappingViewModel>();
		service.AddTransient<MaterialsViewModel>();
		service.AddTransient<MachineConfigViewModel>();
		service.AddTransient<BendSequenceEditorViewModel>();
		service.AddTransient<PPSettingsViewModel>();
		service.AddTransient<CrowningViewModel>();
		service.AddTransient<PressForceHemViewModel>();
		service.AddTransient<IValidationSettingsViewModel, ValidationSettingsViewModel>();
		service.AddSingleton<MachineGeometryConfigViewModel>();
		service.AddTransient<BystronicXMLImporter>();
		service.AddTransient<DelemXMLImporter>();
		service.AddTransient<LvdXMLImporter>();
		service.AddTransient<RadanMDBImporter>();
		service.AddTransient<RadanXMLImporter>();
		service.AddTransient<TrumpfARVImporter>();
		service.AddTransient<TrumpfMDBImporter>();
		service.AddTransient<TrumpfBtdImporter>();
		service.AddTransient<SafanDarleyImporter>();
		service.AddTransient<StepAutomationImporter>();
		service.AddTransient<ImportHelper>();
		service.AddTransient<ISelectMachineView, SelectMachineView>();
		service.AddTransient<ISelectMachineViewModel, SelectMachineViewModel>();
		service.AddTransient<IBendTableViewModel, BendTableViewModel>();
		service.AddTransient<BendDataBaseViewModel>();
		service.AddTransient<ITextInput, TextInput>();
		service.AddTransient<IAssemblyView, AssemblyView>();
		service.AddTransient<IAssemblyViewModel, AssemblyViewModel>();
		service.AddTransient<IIssueViewModel, IssueViewModel>();
		service.AddTransient<IIssueView, IssueView>();
		service.AddTransient<ILegendViewModel, LegendViewModel>();
		service.AddTransient<LegendView>();
		service.AddTransient<L26View>();
		service.AddTransient<L26ViewModel>();
		service.AddTransient<PpScreenshotSettingsView>();
		service.AddTransient<PpScreenshotSettingsViewModel>();
		service.AddSingleton<IArrowFactory, ArrowFactory>();
		service.AddSingleton<IShortcutSettingsCommon, ShortcutSettingsCommon>();
		service.AddTransient<IPopupUnfoldSettingView, PopupUnfoldSettingView>();
		service.AddTransient<IMacroConfigViewModel, MacroConfigViewModel>();
		service.AddSingleton<ToolSetupMemoryViewModel>();
		service.AddSingleton<ToolSetupMemoryView>();
		service.AddSingleton<IBillboardFactory, BillboardFactory>();
		service.AddSingleton<IPopupService, PopupService>();
		service.AddSingleton<IDrawToolProfile, DrawToolProfile>();
		service.AddSingleton<IPPManualSetupView, PPManualSetupView>();
		service.AddSingleton<IPPManualSetupViewModel, PPManualSetupViewModel>();
		service.AddSingleton<IWinDebug, WinDebug>();
		service.AddScoped<WinDebugViewModel>();
		service.AddScoped<ICurrentCalculation, CurrentCalculation>();
		service.AddScoped<IEditToolsMainView, EditToolsMainView>();
		service.AddScoped<IEditToolsMainViewModel, EditToolsMainViewModel>();
		service.AddSingleton<OverviewView>();
		service.AddScoped<OverviewViewModel>();
		service.AddToolCalculationGuiWpf();
		service.AddWpfControls();
		service.AddSingleton<IDockingService, DockingService>();
	}

	public static void UseGuiWpf(this IServiceProvider serviceProvider)
	{
		using (serviceProvider.GetRequiredService<ITelemetrySource>().StartActivity("Use WPF"))
		{
			serviceProvider.UseWpfControls();
			serviceProvider.UseToolCalculationGuiWpf();
			serviceProvider.GetService<IPipeService>()?.Add(20, (string i) => i.Equals("L26Configure"), delegate
			{
				serviceProvider.GetService<L26View>()?.ShowDialog();
				return 0;
			});
			serviceProvider.GetService<IPopupService>().RegisterPopup<ToolSetupMemoryView, ToolSetupMemoryViewModel>();
			IDockingService? service = serviceProvider.GetService<IDockingService>();
			TmpStartPos startPos = new TmpStartPos(250.0, 200.0, IsCenter: false, new Vector2d(50.0, 450.0));
			TmpStartPos startPos2 = new TmpStartPos(320.0, 420.0, IsCenter: false, new Vector2d(50.0, 50.0));
			TmpStartPos startPos3 = new TmpStartPos(800.0, 500.0, IsCenter: true, Vector2d.Zero);
			TmpStartPos startPos4 = new TmpStartPos(400.0, 600.0, IsCenter: false, new Vector2d(50.0, 50.0));
			service.RegisterScopedView<EditFingersView, IEditFingersViewModel>(startPos2);
			service.RegisterScopedView<BendContextView, BendContextViewModel>(startPos4, "l_popup.EditBendContextMenu.Title");
			service.RegisterScopedView<BendContextStepBendView, BendContextStepBendViewModel>(startPos4, "l_popup.EditStepBendContextMenu.Title");
			service.RegisterScopedView<ToolSetupMemoryView, ToolSetupMemoryViewModel>(startPos3);
			service.RegisterViewModelOnly<IEditLiftingAidsViewModel>();
			service.RegisterViewModelOnly<IEditLcbViewModel>();
			service.RegisterScopedView<ToolCalculationOptionView, IToolCalculationOptionViewModel>(startPos4);
			service.RegisterScopedView<SnapPointView, ISnapPointViewModel>(startPos);
			service.RegisterScopedView<EditToolsView, IEditToolsViewModel>(startPos2);
			service.RegisterTransientView<SubToolSectionReplaceView, ISubToolSectionReplaceViewModel>(startPos3);
			service.RegisterTransientView<SubToolSectionView, ISubToolSectionViewModel>(startPos3);
			service.RegisterTransientView<SubToolPieceView, ISubToolPieceViewModel>(startPos3);
		}
	}

	private static void CustomShowView(object v, object vm)
	{
		if (v is FrameworkElement frameworkElement)
		{
			frameworkElement.DataContext = vm;
		}
	}
}
