using System;
using System.Linq;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Markup;
using BendDataBase.WiCAM.Pn4000.pn4.Sym3D.BendSimulation.RadanConfig;
using Telerik.Windows.Controls;
using Telerik.Windows.Controls.Data.PropertyGrid;
using Telerik.Windows.Controls.Primitives;
using WiCAM.Pn4000.Common;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools;
using WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig.Tools.ToolItemViewModels;

namespace WiCAM.Pn4000.PN3D.Popup.UI.Views;

public partial class EditScreenView : UserControl, IComponentConnector
{
	private DataTemplate _geometryFileTemplate;

	private DataTemplate _toolItemViewModelBaseTemplate;

	public EditScreenView()
	{
		InitializeComponent();
	}

	private void PropertyGrid_AutoGeneratingPropertyDefinition(object sender, AutoGeneratingPropertyDefinitionEventArgs e)
	{
		string text = e.PropertyDefinition.AutoGeneratedPath;
		string text2 = "";
		Type type = (sender as RadPropertyGrid).Item.GetType();
		TranslationKeyAttribute translationKeyAttribute = (TranslationKeyAttribute)type.GetProperty(text).GetCustomAttribute(typeof(TranslationKeyAttribute), inherit: true);
		if (translationKeyAttribute != null)
		{
			text = translationKeyAttribute.Key;
		}
		else if (type == typeof(UpperToolPieceViewModel))
		{
			text2 = "l_popup.PunchesView.";
		}
		else if (type == typeof(UpperToolViewModel))
		{
			text2 = "l_popup.PunchesView.";
		}
		else if (type == typeof(LowerToolPieceViewModel))
		{
			text2 = "l_popup.DiesView.";
		}
		else if (type == typeof(LowerToolViewModel))
		{
			text2 = "l_popup.DiesView.";
		}
		else if (type == typeof(PreferredProfileViewModel))
		{
			text2 = "l_popup.PreferredToolsView.";
		}
		else if (type == typeof(UpperToolGroupViewModel))
		{
			text2 = "l_popup.GroupsView.";
		}
		else if (type == typeof(LowerToolGroupViewModel))
		{
			text2 = "l_popup.GroupsView.";
		}
		else if (type == typeof(LowerAdapterViewModel) || type == typeof(UpperAdapterViewModel))
		{
			text2 = "l_popup.AdapterView.";
		}
		if (e.PropertyDefinition.SourceProperty.PropertyType.BaseType == typeof(GeometryFile))
		{
			CreateGeometryTemplate(text);
			e.PropertyDefinition.EditorTemplate = _geometryFileTemplate;
		}
		else if (e.PropertyDefinition.SourceProperty.PropertyType.BaseType == typeof(ToolItemViewModel))
		{
			e.PropertyDefinition.EditorTemplate = _toolItemViewModelBaseTemplate;
		}
		e.PropertyDefinition.DisplayName = (string)Application.Current.TryFindResource(text2 + text);
		string.IsNullOrEmpty(e.PropertyDefinition.DisplayName);
		e.PropertyDefinition.Description = (string)Application.Current.TryFindResource(text2 + text + ".Desc");
		e.PropertyDefinition.GroupName = (string)Application.Current.TryFindResource(text2 + text + ".Grp");
	}

	private void CreateGeometryTemplate(string propertyName)
	{
		_geometryFileTemplate = new DataTemplate
		{
			DataType = typeof(RadAutoCompleteBox)
		};
		if (!_geometryFileTemplate.IsSealed)
		{
			FrameworkElementFactory frameworkElementFactory = new FrameworkElementFactory(typeof(RadAutoCompleteBox));
			UserControl userControl = FindParent<UserControl>(this);
			object value = userControl.DataContext.GetType().GetProperty(propertyName + "s").GetValue(userControl.DataContext);
			frameworkElementFactory.SetBinding(RadAutoCompleteBox.ItemsSourceProperty, new Binding
			{
				Source = value
			});
			frameworkElementFactory.SetBinding(RadAutoCompleteBox.SelectedItemProperty, new Binding(propertyName));
			frameworkElementFactory.SetValue(RadAutoCompleteBox.DisplayMemberPathProperty, "Name");
			frameworkElementFactory.SetValue(RadAutoCompleteBox.WatermarkContentProperty, "Type here");
			frameworkElementFactory.SetValue(RadAutoCompleteBox.TextSearchModeProperty, (object)(TextSearchMode)1);
			frameworkElementFactory.SetValue(RadAutoCompleteBox.AutoCompleteModeProperty, AutoCompleteMode.SuggestAppend);
			frameworkElementFactory.SetValue(RadAutoCompleteBox.NoResultsContentProperty, "No results found");
			frameworkElementFactory.SetValue(RadAutoCompleteBox.SelectionModeProperty, AutoCompleteSelectionMode.Single);
			_geometryFileTemplate.VisualTree = frameworkElementFactory;
			_geometryFileTemplate.Seal();
		}
	}

	public static T FindParent<T>(DependencyObject child) where T : DependencyObject
	{
		DependencyObject dependencyObject = ParentOfTypeExtensions.GetParents(child).FirstOrDefault();
		if (dependencyObject == null)
		{
			return null;
		}
		if (dependencyObject is T result)
		{
			return result;
		}
		return FindParent<T>(dependencyObject);
	}
}
