namespace WiCAM.Pn4000.JobManager;

public static class Sprachen
{
	public static string[,] arrSprache = new string[340, 4]
	{
		{ "0", "leer", "leer", "leer" },
		{ "1", "Text deutsch", "Text englisch", "Text französisch" },
		{ "2", "Info + Maschinen", "Info + Machines", "" },
		{ "3", "PopUp-Check", "PopUp-Check", "" },
		{ "4", "Lizenz-Info", "License-Info", "" },
		{ "5", "Sicherung", "Backup", "" },
		{ "6", "über PNxpert", "about PNxPert", "" },
		{ "7", "lokal", "local", "" },
		{ "8", "PN", "PN", "" },
		{ "9", "Archive", "Archives", "" },
		{ "10", "Filter aus", "Filter off", "" },
		{ "11", "Filter ein", "Filter on", "" },
		{ "12", "Nr.", "No.", "" },
		{ "13", "Name", "Name", "" },
		{ "14", "Modell", "Model", "" },
		{ "15", "Steuerung", "Control", "" },
		{ "16", "Bemerkung", "Remark", "" },
		{ "17", "Datei", "File", "" },
		{ "18", "Titel", "Titel", "" },
		{ "19", "Verzeichnis", "Directory", "" },
		{ "20", "Auto", "Auto", "" },
		{ "21", "Liz.-Nr.", "Lic.-No.", "" },
		{ "22", "Anzahl", "Amount", "" },
		{ "23", "Bedeutung", "Meaning", "" },
		{ "24", "Datum", "Date", "" },
		{ "25", "unbegrenzt", "unlimited", "" },
		{ "26", "bitte Zielverzeichnis auswählen ..", "select target directory ..", "" },
		{ "27", "weitere Dateien hinzufügen ..", "add more files ..", "" },
		{ "28", "ausgewählte Dateien kopieren", "copy selected files", "" },
		{ "29", "Quell-Datei", "Source File", "" },
		{ "30", "Ziel-Datei", "Target File", "" },
		{ "31", "Verzeichnis für Kopie:", "Target directory:", "" },
		{ "32", "weitere", "more", "" },
		{ "33", "Ordner Config öffnen ...", "open Config directory ...", "" },
		{ "34", "bearbeiten", "edit", "" },
		{ "35", "löschen", "delete", "" },
		{ "36", "Ordner öffnen ..", "open directory ..", "" },
		{ "37", "Datei entfernen", "remove file", "" },
		{ "38", "Zieldatei umbenennen", "rename target file", "" },
		{ "39", "", "", "" },
		{ "40", "Versionsnummer", "Version Number", "" },
		{ "41", "PN VIEW", "PN VIEW", "" },
		{ "42", "Grundlizenz", "Basic license", "" },
		{ "43", "PN 2D; Konstruktion und Bemaßung", "PN 2D; Construction and Measuring", "" },
		{ "44", "PN NC; Stanzen, Lasern, Schachtelung gleicher Teile", "PN NC; punching, lasering, nesting of equal parts", "" },
		{ "45", "PN 3D; 3D Konstruktion und Blechabwicklung", "PN 3D; 3D Construction and Unfolding", "" },
		{ "46", "PN 3D ASSEMBLY; Zusammenbauzeichnungen", "PN 3D ASSEMBLY; Assembly Drawings", "" },
		{ "47", "PN 3D LASER; 3- bis 6-Achsen-Lasern", "PN 3D LASER; 3- to 6-Axis-Lasering", "" },
		{ "48", "PN 3D BIEGEN", "PN 3D Bending", "" },
		{ "49", "PN 3D MOTION; 3D Simulation", "PN 3D MOTION; 3D Simulation", "" },
		{ "50", "DXF IN/OUT; Standard 2D/3D Geometrie-Schnittstelle", "DXF IN/OUT; Standard 2D/3D Geometry-Interface", "" },
		{ "51", "IGES IN/OUT; Standard 2D/3D Geometrie-Schnittstelle", "IGES IN/OUT; Standard 2D/3D Geometry-Interface", "" },
		{ "52", "ME 10 IN/OUT; Direkt 2D Geometrie-Schnittstelle", "ME 10 IN/OUT; Direct 2D Geometry-Interface", "" },
		{ "53", "CATIA IN", "CATIA IN", "" },
		{ "54", "PRO-E IN", "PRO-E IN", "" },
		{ "55", "HPGL IN/OUT; Zeichnungsausgabe auf Plotter", "HPGL IN/OUT; Drawings on plotters", "" },
		{ "56", "Solid Works IN", "Solid Works IN", "" },
		{ "57", "CADAM IN", "CADAM IN", "" },
		{ "58", "RPP IN; Rückwärts-Postprozessor in Grafik", "RPP IN; reverse-postprozessor into geometry", "" },
		{ "59", "TOPS IN; Direkt 2D Geometrie-Schnittstelle", "TOPS IN; Direct 2D Geometry-Interface", "" },
		{ "60", "BYSOFT IN; Direkt 2D Geometrie-Schnittstelle", "BYSOFT IN; Direct 2D Geometry-Interface", "" },
		{ "61", "TC-CAPT IN; Direkt 2D CAD + NC Schnittstelle", "TC-CAPT IN; Direct 2D CAD + NC Interface", "" },
		{ "62", "TC-APT IN; Direkt 2D Geometrie-Schnittstelle", "TC-APT IN; Direct 2D Geometry-Interface", "" },
		{ "63", "DWG IN; Direkt 2D/3D Geometrie-Schnittstelle zu Autocad", "DWG IN; Direkt 2D/3D Geometry-Interface for Autocad", "" },
		{ "64", "VDAFS IN; Direkt 2D Geometrie-Schnittstelle", "VDAFS IN; Direct 2D Geometry-Interface", "" },
		{ "65", "IDEAS IN; Direkt 2D Geometrie-Schnittstelle", "IDEAS IN; Direct 2D Geometry-Interface", "" },
		{ "66", "CYCAD OUT; Direkt-Schnittstelle zu Cybelec", "CYCAD OUT; Direct-Interface for Cybelec", "" },
		{ "67", "VBEND OUT; Direkt-Schnittstelle zu Delem", "VBEND OUT; Direct-Interface for Delem", "" },
		{ "68", "BYBEND PART OUT; Direkt-Schnittstelle zu Hämmerle mit MMC-Steuerung", "BYBEND PART OUT; Direct-Interface for Hämmerle with MMC-Steuerung", "" },
		{ "69", "TRUMAGRAPH IN; Direkt 2D Geometrie-Schnittstelle", "TRUMAGRAPH IN; Direkt 2D Geometry-Interface", "" },
		{ "70", "VISUAL NC IN; 2D Geometrie-Schnittstelle zu Visual NC", "VISUAL NC IN; 2D Geometry-Interface zu Visual NC", "" },
		{ "71", "ADCOS BEND OUT; Direkt-Schnittstelle zu Hämmerle mit Infinitron-Steuerung", "ADCOS BEND OUT; Direct-Interface for Hämmerle with Infinitron-Control", "" },
		{ "72", "SEBASTIAN IN; 2D Geometrie-Schnittstelle zu Sebastian / Hackenberg", "SEBASTIAN IN; 2D Geometry-Interface for Sebastian / Hackenberg", "" },
		{ "73", "STEP IN; Standard 2D / 3D Geometrie-Schnittstelle", "STEP IN; Standard 2D / 3D Direct-Interface", "" },
		{ "74", "LUCIA OUT; Direkt-Schnittstelle zu Lucia", "LUCIA OUT; Direct-Interface for Lucia", "" },
		{ "75", "ToPs 600 OUT; Direkt-Schnittstelle zu ToPs 600", "ToPs 600 OUT; Direct-Interface for ToPs 600", "" },
		{ "76", "SOLID-EDGE IN; Direkt-Schnittstelle 3D", "SOLID-EDGE IN; Direct-Interface 3D", "" },
		{ "77", "PNBend OUT; Direkt-Schnittstelle zu PNBend", "PNBend OUT; Direct-Interface for PNBend", "" },
		{ "78", "SAT IN; Direkt 2D/3D Geometrie-Schnittstelle", "SAT IN; Direct 2D/3D Geometry-Interface", "" },
		{ "79", "NC-Express IN; Direkt 2D CAD + NC Schnittstelle", "NC-Express IN; Direct 2D CAD + NC Interface", "" },
		{ "80", "BYSOFT6 IN", "BYSOFT6 IN", "" },
		{ "81", "CUT5 IN", "CUT5 IN", "" },
		{ "82", "XML IN", "XML IN", "" },
		{ "83", "AUTO-LASER; Automatische 2D Laserbearbeitung", "AUTO-LASER; Automatic 2D Laser processing", "" },
		{ "84", "AUTO-PUNCH; Automatische 2D Stanzbearbeitung", "AUTO-PUNCH; Automatic 2D Punch processing", "" },
		{ "85", "NEST-RECHT; Rechteck-Schachtelung ungleicher Teile", "NEST-RECT; Rectangular Nesting of unequal parts", "" },
		{ "86", "NEST-TEILE; Geometrie-Schachtelung ungleicher Teile", "NEST-PART; Geometric Nesting of unequal parts", "" },
		{ "87", "NEST-MANU; Manuelle Schachtelung ungleicher Teile", "NEST-MANU; Manual Nesting of unequal parts", "" },
		{ "88", "REST-PLAT; Resttafelverwaltung", "REST-PLAT; Rest Plate Management", "" },
		{ "89", "SORT-WRKZ; Automatische Werkzeugsortierung", "SORT-TOOL; Automatic Tool Sorting", "" },
		{ "90", "ZEIT-KOSTEN; Erstellung von Fertigungsunterlagen", "TIME-COST; Creation of production paperwork", "" },
		{ "91", "NEST-DBMS; Auftrags-Pool", "NEST-DBMS; Order-Pool", "" },
		{ "92", "VARIANTE; Parametrisierung von NC-Programmen", "VARIANTE; Parameterisation of NC-Programs", "" },
		{ "93", "AUTO-SHEAR; Automatische 2D Scherbearbeitung", "AUTO-SHEAR; Automatic 2D Shear Processing", "" },
		{ "94", "AUTO-LOOP; Automatisches Definieren und Abarbeiten von PN Skripten", "AUTO-LOOP; Automatic Definition and Processing of PN Scripts", "" },
		{ "95", "PN LIFT; Automatische Saugerfindung", "PN LIFT; Automatic Succer Positioning", "" },
		{ "96", "JOB-LOOP; Automatische Schachtelung alle anstehenden Aufträge", "JOB-LOOP; Automatic Nesting of all upcoming Orders", "" },
		{ "97", "PN ENGINE; Automatische Abarbeitung von Scripten", "PN ENGINE; Automatic Processing of Scripts", "" },
		{ "98", "DEVELOP; 3D, 2D, NC Schnittstelle für eigene Entwicklungen", "DEVELOP; 3D, 2D, NC Interface for Development", "" },
		{ "99", "PPSLINK; Grundbaustein für PPS-Anbindung", "PPSLINK; Basic module for PPS-Link", "" },
		{ "100", "PN VIEW; Darstellung von CAD-Modellen 2D/3D und NC", "PN VIEW; Visualization of CAD-Models 2D/3D and NC", "" },
		{ "101", "DNC BASIS; Grundbaustein für DNC-Betrieb", "DNC BASIS; basic module for DNC-Connection", "" },
		{ "102", "PNBend; 3D Bendprogramm GP125", "PNBend; 3D Bendprogram GP125", "" },
		{ "103", "PN BEND", "PN BEND", "" },
		{ "104", "V BEND", "", "V BEND" },
		{ "105", "Lizenznummer unbekannt", "License number unknown", "" },
		{ "106", "Öffnet das PN-Verzeichnis im Windows-Explorer.", "Opens the PN-directory in Windows-Explorer.", "" },
		{ "107", "Öffnet das Archiv-Verzeichnis im Windows-Explorer.", "Opens the Archive-directory in Windows-Explorer", "" },
		{ "108", "Öffnet das lokale Arbeitsverzeichnis im Windows-Explorer", "Opens the local work-directory in Windows-Explorer.", "" },
		{ "109", "Öffnet ein DOS-Fenster im lokalen \nArbeitsverzeichnis (pnusers\\default).", "Opens a DOS Command Window in the local \nwork directory (pnusers\\default).", "" },
		{ "110", "Startet den PopUp-Check erneut und aktualisiert die Ansicht.", "Starts the PopUp-Check again and refreshs the list view.", "" },
		{ "111", "Aktualisiert die Liste mit den Maschinen.", "Refreshs the list with the machines.", "" },
		{ "112", "Die zuletzt verwendete Maschine (in PN) wird in der \nListe markiert. Sie muss nicht gesucht werden. 8-)", "The last used machine (in PN) will be marked in \nthe list. No need to search for it. 8-)", "" },
		{ "113", "Wähle hier die Maschine für PopUp-Check.", "Select the machine for the POPUP-Check.", "" },
		{ "114", "Beliebigen Text zum Filtern der Maschinenliste \neingeben. Groß-/Kleinschreibung ist egal.", "Enter any text for filtering the machine list. \nUpper- or Lowercase doesn't matter.", "" },
		{ "115", "Schaltet den Filter aktiv/inaktiv", "Switch the filter on/off.", "" },
		{ "116", "Markiere diese Option, um alle Dateien aus dem \nVerzeichnis \\u\\pn\\firma zu sichern.", "Check this option to save all files from \ndirectory \\u\\pn\\firma.", "" },
		{ "117", "Markiere diese Option, um alle Dateien aus dem \nVerzeichnis \\u\\pn\\gfiles zu sichern.", "Check this option to save all files from \ndirectory \\u\\pn\\gfiles.", "" },
		{ "118", "Markiere diese Option, um alle Dateien aus dem \nVerzeichnis \\u\\pn\\jobdata\\00 zu sichern.", "Check this option to save all files from \ndirectory \\u\\pn\\jobdata\\00.", "" },
		{ "119", "Markiere diese Option, um alle Dateien aus dem \nVerzeichnis \\u\\pn\\mfiles\\00 und ..\\01 zu sichern.", "Check this option to save all files from \ndirectory \\u\\pn\\mfiles\\00 and ..\\01.", "" },
		{ "120", "Markiere diese Option, um alle Dateien aus dem \nVerzeichnis \\u\\pn\\pfiles\\00 und ..\\01 zu sichern.", "Check this option to save all files from \ndirectory \\u\\pn\\pfiles\\00 and ..\\01.", "" },
		{ "121", "Markiere diese Option, um alle Dateien aus dem \nVerzeichnis \\u\\pn\\machine\\ zu sichern.\nAusnahme: machine_0000.", "Check this option to save all files from \ndirectory \\u\\pn\\machine\\. Exception: machine_0000", "" },
		{ "122", "Hier klicken, um den Zielordner für den Kopiervorgang zu wählen.", "Click here to select the target directory for the copy", "" },
		{ "123", "Hier klicken, um weitere Dateien für die Sicherung zur Liste hinzuzufügen.", "Click here to add more files to the list for the backup.", "" },
		{ "124", "Startet den Kopiervorgang.", "Starts the backup.", "" },
		{ "125", "Soll die Datei $ wirklich gelöscht werden?", "Really delete the file $?", "" },
		{ "126", "Bestätigung erforderlich", "Confirmation required", "" },
		{ "127", "Alle Dateien wurden kopiert.", "All files have been copied.", "" },
		{ "128", "Bitte den USB-Stick nicht vergessen!", "Do not forget to remove the usb stick", "" },
		{ "129", "Kopiervorgang abgeschlossen", "Copy complete", "" },
		{ "130", "FEHLER!", "ERROR!", "" },
		{ "131", "Es ist noch kein Zielverzeichnis ausgewählt.", "Target directory not selected.", "" },
		{ "132", "Dateien für die Sicherung auswählen ..", "Select files for backup ..", "" },
		{ "133", "Fehler beim Öffnen des Verzeichnisses", "Error on opening directory", "" },
		{ "134", "Aktuelle Maschine konnte nicht ermittelt werden.", "Currently used machine could not be identified.", "" },
		{ "135", "Es wurde noch keine Maschine ausgewählt.", "A machine must be selected first.", "" },
		{ "136", "Die Datei", "The file", "" },
		{ "137", "wurde verschoben nach:", "has been moved to", "" },
		{ "138", "aktuelle Sortier-Liste", "current Sort-List", "" },
		{ "139", "noch nicht sortierte Werkzeuge", "not yet sorted tools", "" },
		{ "140", "zurück", "back", "" },
		{ "141", "Dialog schließen.", "Close this window", "" },
		{ "142", "Änderungen übernehmen", "Apply changes", "" },
		{ "143", "Übernimmt die Änderungen in die Datei TOOL_SORT_.TXT.", "Save changes into the file TOOL_SORT_.TXT.", "" },
		{ "144", "Tool-ID", "Tool-ID", "" },
		{ "145", "Typ", "Type", "" },
		{ "146", "X-Dim", "X-Dim", "" },
		{ "147", "Y-Dim", "Y-Dim", "" },
		{ "148", "D-Dim", "D-Dim", "" },
		{ "149", "Einbau-Winkel", "Built-In-Angle", "" },
		{ "150", "Sort-Winkel", "Sort-Angle", "" },
		{ "151", "Rund", "Round", "" },
		{ "152", "Rechteck+Rund", "Rect+Round", "" },
		{ "153", "Quadrat", "Square", "" },
		{ "154", "Rechteck", "Rectangle", "" },
		{ "155", "Gewinde", "Thread", "" },
		{ "156", "Fräser", "Cutter", "" },
		{ "157", "Quadrat+Rund", "Square+Round", "" },
		{ "158", "Langloch", "Oblong", "" },
		{ "159", "Sonderform", "Spec.Shape", "" },
		{ "160", "Körner", "Centerpoint", "" },
		{ "161", "Laser", "Laser", "" },
		{ "162", "n.a.", "n.a.", "" },
		{ "163", "Umform", "Forming", "" },
		{ "164", "Prägen", "Emboss", "" },
		{ "165", "Bogen", "Banana", "" },
		{ "166", "Radius", "Radius", "" },
		{ "167", "Dreieck", "Triangle", "" },
		{ "168", "Schlitz", "Slit", "" },
		{ "169", "Sicken schnell", "Fast Beading", "" },
		{ "170", "Signieren", "Signing", "" },
		{ "171", "MultiCut", "Multicut", "" },
		{ "172", "Kiemen", "Louvre", "" },
		{ "173", "Sicken", "Beading", "" },
		{ "174", "Durchzug", "Extrusion", "" },
		{ "175", "Senken", "Counter Sink", "" },
		{ "176", "Trennen", "Seperating", "" },
		{ "177", "MultiShear", "MultiShear", "" },
		{ "178", "MultiBend", "MultiBend", "" },
		{ "179", "Rollschneiden", "Roller Shearing", "" },
		{ "180", "Rollkneifen", "Roller Pinching", "" },
		{ "181", "Rollabsetzen", "Roller Offsetting", "" },
		{ "182", "Rollsicken", "Roller Beading", "" },
		{ "183", "Gravieren", "Engraving", "" },
		{ "184", "Rollrändeln", "Roller Knurl", "" },
		{ "185", "Kalibrieren", "Calibrating", "" },
		{ "186", "Laserschutzwerkzeug", "Laser Protection", "" },
		{ "187", "Rollentgraten", "Roller Deburring", "" },
		{ "188", "Prägeentgraten", "Emboss Deburring", "" },
		{ "189", "Zur dieser Maschine exisitert keine PNLINK__CONFIG.TXT!", "For this machine the file PNLINK__CONFIG.TXT doesn't exist!", "" },
		{ "190", "PNLINK__CONFIG.TXT von machine_0000 kopieren und öffnen", "copy PNLINK__CONFIG.TXT from machine_0000 and open it in editor", "" },
		{ "191", "Datei nicht gefunden: \n\n", "File not found: \n\n", "" },
		{ "192", "Einzelteil: ", "Single part: ", "" },
		{ "193", "Platine: ", "Plate: ", "" },
		{ "194", "Verschiedenes", "Miscellaneous", "" },
		{ "195", "Prüfe Varianten Makros", "Check Parametric Macros", "" },
		{ "196", "Variante", "Parametric", "" },
		{ "197", "Anzeigen in Liste", "Show in list", "" },
		{ "198", "prüfe vorhandene PTT Einträge", "check existing PTT entries", "" },
		{ "199", "Edit Vorlage", "Edit template", "" },
		{ "200", "AUTO-BEVEL; Fasen schneiden", "AUTO-BEVEL; Cutting bevels", "" },
		{ "201", "Fertig. Der Lift wurde unter der Bezeichnung\n\nLIFT2PN_M", "Done. The Lift has been stored under the name\n\nLIFT2PN_M", "" },
		{ "202", "\n\nim CAD-Archiv 1 abgelegt.", "\n\ninto the CAD archive 1.", "" },
		{ "203", "CAM-Assembly; Baugruppe", "CAM-Assembly", "" },
		{ "204", "AUTO-MILL; Fräsen", "AUTO-MILL; Routing", "" },
		{ "205", "SQL-Material; Material Datenbank", "SQL-Material; Material Database", "" },
		{ "206", "SQL-Order; Auftrags Datenbank", "SQL-Order; Order Database", "" },
		{ "207", "SQL-Archive; Archiv Datenbank", "SQL-Archive; Archive Database", "" },
		{ "208", "Bezeichnung", "Name", "" },
		{ "209", "Bemerkung", "Remark", "" },
		{ "210", "Winkel für Sortierung angeben", "Define angle for sorting", "" },
		{ "211", "Berücksichtige Winkel", "Consider angle", "" },
		{ "212", "Zurück", "Back", "" },
		{ "213", "Änderungen speichern", "save changes", "" },
		{ "214", "Noch nicht sortierte Werkzeuge: ", "Not yet sorted tools: ", "" },
		{ "215", "Aktuelle Sort-Liste: ", "Current Sort-List: ", "" },
		{ "216", "Änderungen wurden noch nicht gespeichert!\n\nFenster wirklich schließen?", "Changes haven't been saved yet!\n\nReally close the window?", "" },
		{ "217", "Warnung!", "Warning!", "" },
		{ "218", "Stat-Nr.", "Stat-No.", "" },
		{ "219", "Stat-Name", "Stat-Name", "" },
		{ "220", "Stations-Nummer", "Station Number", "" },
		{ "221", "Stations-Name", "Station Name", "" },
		{ "222", "Bemerkung", "Remark", "" },
		{ "223", "Bezeichnung", "Label", "" },
		{ "224", "Multitool", "Multitool", "" },
		{ "225", "Verwaiste Einträge aus der Toolsortliste entfernt:  ", "Orphaned entries removed from Toolsort list:  ", "" },
		{ "226", "Doppelte Tool-ID's aus der Werkzeugliste entfernt:  ", "Double Tool ID's removed from Tool list:  ", "" },
		{ "227", "Werkzeug ID:\nWerkzeugtyp:\n:Bezeichnung:\nBemerkung:\nX Dim:\nY Dim:\nD Dim:\nStations-Typ:\nStations-Nummer:", "Tool ID:\nTool type:\nLabel:\nRemark:\nX Dim:\nY Dim:\nD Dim:\nStation type:\nStation number:", "" },
		{ "228", "OK", "OK", "" },
		{ "229", "Abbruch", "Cancel", "" },
		{ "230", "Bohrer", "Drill", "" },
		{ "231", "MicroTool", "MicroTool", "" },
		{ "232", "Recht-Schere", "Rect-Shear", "" },
		{ "233", "darüber einfügen", "insert above", "" },
		{ "234", "darunter einfügen", "insert below", "" },
		{ "235", "merke {0} selektierte", "memorise {0} selected", "" },
		{ "236", "alle auswählen", "select all", "" },
		{ "237", "selektierte entfernen", "remove selected", "" },
		{ "238", "Zeile duplizieren", "duplicate line", "" },
		{ "239", "Sort Liste ...", "Sort List ...", "" },
		{ "240", "Änderungen wurden gespeichert in:", "Changes have been saved to:", "" },
		{ "241", "Erzeuge PTT", "Create PTT", "" },
		{ "242", "{0} PTT-Daten wurden in die Zwischenablage kopiert.", "{0} PTT data have been copied to the clipboard", "" },
		{ "243", "Es wurden KEINE PTT Daten erzeugt!", "NO PTT data have been created!", "" },
		{ "244", "Erzeugt für die aktuellen Werkzeuge PTT Einträge basierend auf der \nVorlage in der Datei 'ptt.txt' und kopiert sie in die Zwischenablage.", "Creates PTT entries based on the template in the file 'ptt.txt' \nand copies them into the clipboard.", "" },
		{ "245", "Öffnet die Datei 'ptt.txt' im Editor", "Opens the file 'ptt.txt' in the editor", "" },
		{ "246", "Prüft, welche PTTs bereits vorhanden sind. Dann werden mit der \nFunktion 'erzeuge PTT' nur noch die fehlenden erzeugt.", "Check which PTT entries are already available. Then only missing \nentries will be created with the function 'Create PTT'.", "" },
		{ "247", "Markieren, um die Multitools jeweils zusammen zu sortieren.", "Tag this to sort the tools of the multitools together.", "" },
		{ "248", "Bezeichnung anzeigen", "Show label", "" },
		{ "249", "Bemerkung anzeigen", "Show remark", "" },
		{ "250", "Stationsnummer anzeigen", "Show station number", "" },
		{ "251", "Stationsname anzeigen", "Show station name", "" },
		{ "252", "Speichert die aktuelle Sortier-Reihenfolge im linken Fenster in die Datei TOOLSORT_LIST_.TXT.", "Saves the current sort order from the left window into the file TOOLSORT_LIST_.TXT.", "" },
		{ "253", "Schließt dieses Fenster ohne die Änderungen zu speichern.", "Closes this window without saving the changes.", "" },
		{ "254", "vorhandene Makros", "existing macros", "" },
		{ "255", "enthalten in", "contained in", "" },
		{ "256", "Ergebnis in die Zwischenablage kopieren", "copy results to clipboard", "" },
		{ "257", "Ergebnis wurde in die Zwischenablage kopiert.", "Results have been copied to clipboard", "" },
		{ "258", "Kopiert das Ergebnis für alle Makros als Text in die Zwischenablage", "Copies the result for all macros as text into the clipboard.", "" },
		{ "259", "Variante markieren, um die Abhängigkeiten zu zeigen.", "Mark parametric to view the dependency.", "" },
		{ "260", "Zeigt an, welche Varianten-Makros in welchen Varianten enthalten sind.", "Shows which parametric macros are included in other parametrics.", "" },
		{ "261", "Texte für Auftragspool anpassen", "Customise texts for order pool", "" },
		{ "262", "Suche Anpassungen", "Search Customisation", "" },
		{ "263", "Texte für Auftragspool", "Text for Order Pool", "" },
		{ "264", "Kann die Datei TAB001 nicht finden", "Cannot find the file TAB001", "" },
		{ "265", "Typ", "Type", "" },
		{ "266", "Verschiebt den aktuellen Eintrag um 1 Position nach oben (Shift-Auf)", "Moves the current entry 1 position up (Shift-Up)", "" },
		{ "267", "Texte Bearbeiten", "Edit texts", "" },
		{ "268", "Original", "Original", "" },
		{ "269", "Angepasst", "Customized", "" },
		{ "270", "Mit gleicher ... pro Job", "With same ... per job", "" },
		{ "271", "Verschiebt den aktuellen Eintrag um 5 Positionen nach oben (Ctrl-Auf)", "Moves the current entry 5 positions up (Ctrl-Up)", "" },
		{ "272", "Verschiebt den aktuellen Eintrag um 1 Position nach unten (Shift-Ab)", "Moves the current entry 1 position down (Shift-Down)", "" },
		{ "273", "Verschiebt den aktuellen Eintrag um 5 Positionen nach unten (Ctrl-Ab)", "Moves the current entry 5 positions down (Ctrl-Down)", "" },
		{ "274", "Anzahl Zeichen\n(max. 500)", "Quantity of Character\n(max. 500)", "" },
		{ "275", "suche Anpassungen", "search custom texts", "" },
		{ "276", "alles zurücksetzen", "reset all", "" },
		{ "277", "Dateien speichern", "save files", "" },
		{ "278", "Anpassung der Texte für TAB001 und andere Popups", "Customisation of the texts from TAB001 and other popups", "" },
		{ "279", "setzt alle Texte auf den Standard zurück", "all texts are reset to default", "" },
		{ "280", "bricht die aktuelle Aktion ab", "cancellation of the current action", "" },
		{ "281", "speichert die aktuellen Texte in die entsprechenden Popups", "stores the current texts into the corresponding popups", "" },
		{ "282", "liest die aktuellen angepassten Texte und TAB001-Einstellungen \nein und zeigt sie in der Liste an", "reads the current customized texts \nand shows them in the list", "" },
		{ "283", "zeigt ALLE Einträge aus dem TAB001 in der Liste", "shows ALL entries from TAB001 in the list", "" },
		{ "284", "zeigt nur aktive Einträge aus dem TAB001 in der Liste", "shows only active entries from TAB001 in the list", "" },
		{ "285", "zeigt nur Einträge, die im PDB111 enthalten sind", "shows only entries which are contained in PDB111", "" },
		{ "286", "Zeigt die Summe der 'aktiven' Zeichen aus dem TAB001. \nZu den tatsächlichen Buchstaben werden noch die\nFormat-Zeichen hinzugerechnet, sowie für jeden\nEintrag noch ein zusätzliches Trennzeichen.\nDie Anzahl sollte 500 nicht überschreiten.", "Shows the sum of all 'active' Character from the\nTAB001. The format characters are added to the \nactual character as well as a seperator.\nThe total amount shall not exceed 500.", "" },
		{ "287", "Suche Makros ...", "searching macros ...", "" },
		{ "288", "FEHLER: Datei nicht gefunden", "ERROR: File not found", "" },
		{ "289", "Keine angepasste TAB001 gefunden! \nReihenfolge der Einträge wird aus Standard TAB001 übernommen.", "No customised TAB001 found!\nSort order is taken from standard TAB001", "" },
		{ "290", "Schreiben der Dateien", "Writing the files", "" },
		{ "291", "Schaltet alle Checkboxen gemeinsam um", "Switches all checkboxes together", "" },
		{ "292", "Kann die Datei {0} nicht finden!", "Cannot find the file {0}!", "" },
		{ "293", "Schreibe Dateien", "Write files", "" },
		{ "294", "Sicherungskopie erstellen", "Create backup", "" },
		{ "295", "Erzeugt eine Kopie der vorhandenen Dateien mit _Datum_Uhrzeit", "Creates a backup of the existing files with _date_time", "" },
		{ "296", "ALMA IN; Schnittstelle", "ALMA IN; interface", "" },
		{ "297", "ASCO IN; Schnittstelle", "ASCO IN; interface", "" },
		{ "298", "Fehler", "Error", "" },
		{ "299", "Die Datei UNLOAD___LOAD_.TXT konnte nicht gelesen werden.", "Couldn't read the file UNLOAD___LOAD_.TXT", "" },
		{ "300", "Reserveplätze", "Reserve Positions", "" },
		{ "301", "Reserveplätze ausgeben", "Write reserve positions", "" },
		{ "302", "Nummern der Reserveplätze ausgeben", "Write numbers of reserve positions", "" },
		{ "303", "Die Liftdaten wurden im Archiv {0} unter der Bezeichnung {1} abgelegt.", "The lift data has been saved in archive {0} under the name {1}.", "" },
		{ "304", "Verschiebung in X", "Offset in X", "" },
		{ "305", "Verschiebung in Y", "Offset in Y", "" },
		{ "306", "Berechnen", "Calculate", "" },
		{ "307", "Backup anlegen", "Create Backup", "" },
		{ "308", "Schreibe Datei", "Write File", "" },
		{ "309", "Original", "Original", "" },
		{ "310", "Modifiziert", "Modified", "" },
		{ "311", "Die Datei \n\n {0} \n\nwurde neu erstellt.", "The file \n {0} \nhas been created.", "" },
		{ "312", "Berechnet die Verschiebung und schreibt die Daten in den Tab 'Modifiziert'.", "Calculates the offset and writes the data into the tab 'Modified'.", "" },
		{ "313", "Schreibt die Daten in die Datei UNLOAD___LOAD_.TXT.", "Writes the data into the file UNLOAD___LOAD_.TXT.", "" },
		{ "314", "Wenn markiert, wird vor dem Überschreiben ein Backup der Datei angelegt (UNLOAD___LOAD_.TXT_jjjjmmtt_hhmmss).", "If checked, a backup file will be created before overwriting (UNLOAD___LOAD_.TXT_yyyymmdd_hhmmss).", "" },
		{ "315", "", "", "" },
		{ "316", "", "", "" },
		{ "317", "", "", "" },
		{ "318", "", "", "" },
		{ "319", "", "", "" },
		{ "320", "", "", "" },
		{ "321", "", "", "" },
		{ "322", "", "", "" },
		{ "323", "", "", "" },
		{ "324", "", "", "" },
		{ "325", "", "", "" },
		{ "326", "", "", "" },
		{ "327", "", "", "" },
		{ "328", "", "", "" },
		{ "329", "", "", "" },
		{ "330", "", "", "" },
		{ "331", "", "", "" },
		{ "332", "", "", "" },
		{ "333", "", "", "" },
		{ "334", "", "", "" },
		{ "335", "", "", "" },
		{ "336", "", "", "" },
		{ "337", "", "", "" },
		{ "338", "", "", "" },
		{ "339", "", "", "" }
	};
}
