using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Markup;
using Telerik.Windows.Controls;
using Telerik.Windows.Controls.Charting;

namespace WiCAM.Pn4000.GuiWpf.Ui3D.MachineConfig;

public partial class CrowningView : UserControl, IComponentConnector
{
	public CrowningView()
	{
		InitializeComponent();
	}

	private void Selector_OnSelectionChanged(object sender, SelectionChangeEventArgs e)
	{
		UpdateChart();
	}

	private void UserControl_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
	{
		if (base.DataContext is CrowningViewModel crowningViewModel)
		{
			crowningViewModel.DataChanged += UpdateTable;
			UpdateTable();
		}
	}

	private void UpdateTable()
	{
		if (!(base.DataContext is CrowningViewModel crowningViewModel))
		{
			return;
		}
		Datatable.Columns.Clear();
		GridViewDataColumn gridViewDataColumn = new GridViewDataColumn();
		gridViewDataColumn.Width = 150.0;
		gridViewDataColumn.Header = "Material Grp Id";
		gridViewDataColumn.DataMemberBinding = new Binding("MatGrpId");
		Datatable.Columns.Add(gridViewDataColumn);
		GridViewDataColumn gridViewDataColumn2 = new GridViewDataColumn();
		gridViewDataColumn2.Width = 150.0;
		gridViewDataColumn2.Header = "Thickness";
		gridViewDataColumn2.DataMemberBinding = new Binding("Thickness");
		Datatable.Columns.Add(gridViewDataColumn2);
		int num = 0;
		foreach (CrowningColumnViewModel column in crowningViewModel.Columns)
		{
			GridViewDataColumn gridViewDataColumn3 = new GridViewDataColumn();
			gridViewDataColumn3.Width = 150.0;
			gridViewDataColumn3.Header = column.Length.ToString();
			gridViewDataColumn3.DataMemberBinding = new Binding($"Values[{num++}]");
			Datatable.Columns.Add(gridViewDataColumn3);
		}
		Datatable.FrozenColumnCount = 2;
	}

	public void UpdateChart()
	{
		if (!(base.DataContext is CrowningViewModel crowningViewModel))
		{
			return;
		}
		radChart.DefaultView.ChartTitle.Content = "Crwoning Values";
		radChart.DefaultView.ChartLegend.Header = "Legend";
		radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = true;
		radChart.DefaultView.ChartArea.DataSeries.Clear();
		radChart.DefaultView.ChartArea.AxisX.Title = "Bend Length";
		radChart.DefaultView.ChartArea.AxisX.AutoRange = true;
		radChart.DefaultView.ChartArea.AxisX.DefaultLabelFormat = "N0";
		radChart.DefaultView.ChartArea.AxisY.Title = "Crowning";
		radChart.DefaultView.ChartArea.AxisY.AutoRange = true;
		radChart.DefaultView.ChartArea.AxisY.DefaultLabelFormat = "N3";
		double val = double.MaxValue;
		double val2 = 0.0;
		foreach (object selectedItem in Datatable.SelectedItems)
		{
			CrowningItemViewModel crowningItemViewModel = selectedItem as CrowningItemViewModel;
			DataSeries dataSeries = new DataSeries();
			dataSeries.Definition = new LineSeriesDefinition();
			dataSeries.LegendLabel = $"Mat: {crowningItemViewModel.MatGrpId} Thicknes: {crowningItemViewModel.Thickness}";
			int num = 0;
			double[] values = crowningItemViewModel.Values;
			foreach (double num2 in values)
			{
				dataSeries.Add(new DataPoint(crowningViewModel.Columns[num++].Length, num2));
				val = Math.Min(num2, val);
				val2 = Math.Max(num2, val2);
			}
			radChart.DefaultView.ChartArea.DataSeries.Add(dataSeries);
		}
	}
}
