using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using WiCAM.Pn4000.Archive.Browser;
using WiCAM.Pn4000.Archive.Browser.ArchiveCad;
using WiCAM.Pn4000.Archive.Browser.Classes;
using WiCAM.Pn4000.Archive.Browser.Controllers;
using WiCAM.Pn4000.Archive.Browser.Helpers;
using WiCAM.Pn4000.Archives.Cad;
using WiCAM.Pn4000.Archives.Variants;
using WiCAM.Pn4000.Common;
using WiCAM.Pn4000.JobManager;
using WiCAM.Pn4000.WpfControls;

namespace WiCAM.Pn4000.Archive.Browser.ArchiveVariant
{
	internal class VariantArchiveController : ArchiveControllerBase, IArchivController
	{
		private static VariantArchiveController _instance;

		public readonly static DependencyProperty ArchiveContentCollectionProperty;

		private readonly static string __hiddenColumnNames;

		private List<VariantInfo> _allItems;

		private List<VariantInfo> _selectedItems;

		private WpfDataGridController<VariantInfo> _gridController;

		private bool _selectedState;

		private VariantDataRepository _repository;

		public ObservableCollection<VariantInfo> ArchiveContent
		{
			get
			{
				return (ObservableCollection<VariantInfo>)base.GetValue(VariantArchiveController.ArchiveContentCollectionProperty);
			}
			set
			{
				base.SetValue(VariantArchiveController.ArchiveContentCollectionProperty, value);
			}
		}

		public static VariantArchiveController Instance
		{
			get
			{
				if (VariantArchiveController._instance == null)
				{
					Logger.Verbose("Initialize VariantArchiveController");
					VariantArchiveController._instance = new VariantArchiveController();
				}
				return VariantArchiveController._instance;
			}
		}

		static VariantArchiveController()
		{
			VariantArchiveController.ArchiveContentCollectionProperty = DependencyProperty.Register("ArchiveContent", typeof(ObservableCollection<VariantInfo>), typeof(CadPartArchiveController));
			VariantArchiveController.__hiddenColumnNames = "Rowid;";
		}

		private VariantArchiveController()
		{
			this._repository = new VariantDataRepository();
			this._allItems = new List<VariantInfo>();
			this._selectedItems = new List<VariantInfo>();
			this.ArchiveContent = new ObservableCollection<VariantInfo>();
		}

		public void ApplyGridSettings(bool isMultiSelect)
		{
			this._gridController.ApplySettings(isMultiSelect);
		}

		public void ChangeSelection(bool isSelected)
		{
			if (!isSelected)
			{
				this._grid.UnselectAll();
			}
			else
			{
				this._grid.SelectAll();
			}
			try
			{
				for (int i = 0; i < this._grid.Items.Count; i++)
				{
					(this._grid.Items[i] as CadPartInfo).IsSelected = isSelected;
				}
			}
			catch (Exception exception)
			{
				Logger.Exception(exception);
			}
		}

		public void DeleteSelected()
		{
			List<VariantInfo> variantInfos;
			if (this._grid.SelectionMode != DataGridSelectionMode.Extended)
			{
				variantInfos = new List<VariantInfo>();
				if (this._grid.SelectedItem is VariantInfo)
				{
					variantInfos.Add((VariantInfo)this._grid.SelectedItem);
				}
			}
			else
			{
				variantInfos = this.ArchiveContent.ToList<VariantInfo>().FindAll((VariantInfo x) => x.IsSelected);
			}
			foreach (VariantInfo variantInfo in variantInfos)
			{
				string str = this._repository.DeleteOne(variantInfo);
				if (string.IsNullOrEmpty(str))
				{
					this._repository.DeleteFiles(variantInfo);
					this.ArchiveContent.Remove(variantInfo);
					if (EnumerableHelper.IsNullOrEmpty(this._selectedItems) || !this._selectedItems.Contains(variantInfo))
					{
						continue;
					}
					this._selectedItems.Remove(variantInfo);
				}
				else
				{
					Logger.Error(str);
				}
			}
		}

		public void ExportToCsv()
		{
			ExcelCsvExportHelper.ToCsvFromWpfDataGrid<CadPartInfo>(this.ArchiveContent, this._grid, "varArchive.csv");
			ProcessHelper.ExecuteNoWait("varArchive.csv", string.Empty);
		}

		private void FilterControl_FilterTextChanged(object sender, RoutedEventArgs e)
		{
			this._repository.ByFilter(this._archiveFilterCriteria.ListFilters);
			List<VariantInfo> variantInfos = this._repository.ByDateInterval(this._archiveFilterCriteria.DateFrom, this._archiveFilterCriteria.DateTill);
			this.SetPartListData(variantInfos);
		}

		private void Grid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			if (!AppArguments.Instance.IsMultiselect && this._gridController.HiddenColumns.IndexOf("IsSelected;", StringComparison.CurrentCultureIgnoreCase) == -1)
			{
				WpfDataGridController<VariantInfo> wpfDataGridController = this._gridController;
				wpfDataGridController.HiddenColumns = string.Concat(wpfDataGridController.HiddenColumns, "IsSelected;");
			}
			this._gridController.ApplySettings(AppArguments.Instance.IsMultiselect);
		}

		private void Grid_PreviewMouseDoubleClick(object sender, MouseButtonEventArgs e)
		{
			DependencyObject dependencyObject = base.GetDependencyObject((DependencyObject)e.OriginalSource, typeof(DataGridCell));
			if (dependencyObject != null)
			{
				DataGridRow isSelected = WpfVisualHelper.FindVisualParent<DataGridRow>(dependencyObject as UIElement);
				if (isSelected != null)
				{
					try
					{
						CadPartInfo item = (CadPartInfo)isSelected.Item;
						item.IsSelected = true;
						isSelected.IsSelected = item.IsSelected;
						e.Handled = true;
						base.ButtokOkClick();
					}
					catch (Exception exception)
					{
						Logger.Exception(exception);
					}
				}
			}
		}

		private void Grid_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
		{
			Predicate<VariantInfo> predicate = null;
			if (this._grid.SelectionMode != DataGridSelectionMode.Extended)
			{
				return;
			}
			IInputElement inputElement = this._grid.InputHitTest(e.GetPosition(this._grid));
			if (inputElement != null)
			{
				DataGridRow dataGridRow = WpfVisualHelper.FindVisualParent<DataGridRow>(inputElement as UIElement);
				if (dataGridRow != null)
				{
					try
					{
						VariantInfo item = (VariantInfo)dataGridRow.Item;
						DataGridCell dataGridCell = WpfVisualHelper.FindVisualParent<DataGridCell>(inputElement as UIElement);
						if (dataGridCell == null || dataGridCell.Column.DisplayIndex > 1)
						{
							for (int i = this._grid.SelectedItems.Count - 1; i >= 0; i--)
							{
								List<VariantInfo> variantInfos = this._selectedItems;
								Predicate<VariantInfo> predicate1 = predicate;
								if (predicate1 == null)
								{
									Predicate<VariantInfo> rowid = (VariantInfo x) => x.Rowid == ((VariantInfo)this._grid.SelectedItems[i]).Rowid;
									Predicate<VariantInfo> predicate2 = rowid;
									predicate = rowid;
									predicate1 = predicate2;
								}
								if (variantInfos.Find(predicate1) == null)
								{
									this._grid.SelectedItems.RemoveAt(i);
								}
							}
							dataGridRow.IsSelected = true;
						}
						else
						{
							if (item.IsSelected)
							{
								if (this._selectedItems.Contains(item))
								{
									this._selectedItems.Remove(item);
								}
							}
							else if (!this._selectedItems.Contains(item))
							{
								this._selectedItems.Add(item);
							}
							bool isSelected = !item.IsSelected;
							bool flag = isSelected;
							dataGridRow.IsSelected = isSelected;
							item.IsSelected = flag;
						}
						this.LoadCadgeo(item);
						if (this._isShiftPressed)
						{
							int count = this._grid.SelectedItems.Count - 1;
							this._lastSelectedIndex = this._grid.Items.IndexOf(this._grid.SelectedItems[count]);
							if (this._lastSelectedIndex < this._firstSelectedIndex)
							{
								int num = this._lastSelectedIndex;
								this._lastSelectedIndex = this._firstSelectedIndex;
								this._firstSelectedIndex = num;
							}
							for (int j = this._firstSelectedIndex; j <= this._lastSelectedIndex; j++)
							{
								VariantInfo variantInfo = this._grid.Items[j] as VariantInfo;
								variantInfo.IsSelected = true;
								if (!this._selectedItems.Contains(variantInfo))
								{
									this._selectedItems.Add(variantInfo);
								}
								this._grid.SelectedItems.Add(this._grid.Items[j]);
							}
							this._isShiftPressed = false;
						}
					}
					catch (Exception exception)
					{
						Logger.Exception(exception);
					}
				}
			}
		}

		private void Grid_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			if (!EnumerableHelper.IsNullOrEmpty(e.AddedItems))
			{
				CadPartInfo item = e.AddedItems[0] as CadPartInfo;
				if (item != null)
				{
					this.LoadCadgeo(item);
				}
			}
		}

		public ObservableCollection<WpfGridColumnInfo> GridColumnsConfiguration()
		{
			return this._gridController.GridColumnsConfiguration();
		}

		public void Initialize(MainWindow mainWindow)
		{
			ArchiveControllerBase.OkClickHandler = new Action(this.OkButtonClick);
			AppConfiguration.Erg0Format = 1;
			base.InitializeBase(mainWindow, typeof(VariantInfo), AppConfiguration.Instance.DataListCaptions, WiCAM.Pn4000.Archive.Browser.Classes.CS.VarFilter);
			VariantArchiveController variantArchiveController = this;
			this._mainWindow.WriteErg0Handler = new Action(variantArchiveController.WriteErg0File);
			VariantArchiveController variantArchiveController1 = this;
			this._mainWindow.ConfigurationColumnsHandler = new Func<ObservableCollection<WpfGridColumnInfo>>(variantArchiveController1.GridColumnsConfiguration);
			this._mainWindow.ApplyGridSettingsHandler = new Action<bool>(this.SaveGridColumnSettings);
			VariantArchiveController variantArchiveController2 = this;
			this._mainWindow.GridSelectionHandler = new Action<bool>(variantArchiveController2.ChangeSelection);
			VariantArchiveController variantArchiveController3 = this;
			this._mainWindow.DeleteSelectedHandler = new Action(variantArchiveController3.DeleteSelected);
			VariantArchiveController variantArchiveController4 = this;
			this._mainWindow.ExportToCsvHandler = new Action(variantArchiveController4.ExportToCsv);
			VariantArchiveController variantArchiveController5 = this;
			this._mainWindow.InitializeMainWindowHandler = new Action(variantArchiveController5.InitializeMainWindowToolbar);
			this._mainWindow.PreviewKeyUp += new KeyEventHandler(this.Shift_KeyUp);
			this._mainWindow.PreviewKeyDown += new KeyEventHandler(this.Shift_KeyDown);
			this._mainWindow.BtnDelete.Visibility = Visibility.Hidden;
			this._grid.Name = "varGrid";
			Style item = (Style)this._mainWindow.Resources["styleRightAlignedCell"];
			this._gridController = new WpfDataGridController<VariantInfo>(this._grid, "WiCAM.ArchivBrowser", AppConfiguration.Instance.ListConfiguration, null, item, null, AppArguments.Instance.IsMultiselect)
			{
				HiddenColumns = VariantArchiveController.__hiddenColumnNames,
				IsDragDropEnabled = false
			};
			this._grid.SelectionChanged += new SelectionChangedEventHandler(this.Grid_SelectionChanged);
			this._grid.PreviewMouseDoubleClick += new MouseButtonEventHandler(this.Grid_PreviewMouseDoubleClick);
			this._grid.MouseRightButtonUp += new MouseButtonEventHandler(this.Grid_MouseRightButtonUp);
			this._grid.PreviewMouseLeftButtonDown += new MouseButtonEventHandler(this.Grid_PreviewMouseLeftButtonDown);
			this._grid.AutoGeneratedColumns += new EventHandler(this.Grid_AutoGeneratedColumns);
			this._grid.PreviewKeyDown += new KeyEventHandler(this.Grid_PreviewKeyDown);
			this._filterControl.FilterTextChanged += new RoutedEventHandler(this.FilterControl_FilterTextChanged);
			base.InitializeFilters(typeof(VariantInfo));
		}

		public void InitializeMainWindowToolbar()
		{
			base.InitializeFiltersToolbar(this._repository.ConnectionString);
			this._repository.ReadAsyncron(new Action(this.SetPartListData));
		}

		private void LoadCadgeo(CadPartInfo part)
		{
			base.LoadCadgeoPreview(part.Path(), "Variant", part.PartName, 0, 0);
		}

		private void OkButtonClick()
		{
			this.WriteErg0File();
		//	this._mainWindow.Close();
		}

		private void SaveGridColumnSettings(bool isMultiSelect)
		{
			this.ApplyGridSettings(isMultiSelect);
			this._gridController.Save();
		}

		public void SaveSettings()
		{
			this._gridController.Save();
			if (!this._archiveFilterCriteria.Save())
			{
				Logger.Error("Problems writing archive filter criteria!");
			}
		}

		private void SetPartListData()
		{
			List<VariantInfo> parts = this._repository.Parts;
			List<VariantInfo> variantInfos = parts;
			this._allItems = parts;
			this.SetPartListData(variantInfos);
		}

		private void SetPartListData(List<VariantInfo> list)
		{
			this.ArchiveContent.Clear();
			if (!EnumerableHelper.IsNullOrEmpty(list))
			{
				foreach (VariantInfo variantInfo in list)
				{
					this.ArchiveContent.Add(variantInfo);
				}
			}
			int count = 0;
			if (!EnumerableHelper.IsNullOrEmpty(this.ArchiveContent))
			{
				count = this.ArchiveContent.Count;
			}
			int num = 0;
			if (!EnumerableHelper.IsNullOrEmpty(this._allItems))
			{
				num = this._allItems.Count;
			}
			this._mainWindow.StatusText.Text = string.Format(CultureInfo.CurrentCulture, StringResourceHelper.Instance.FindString("MessageFilesAmount"), count, num);
			string searchString = AppArguments.Instance.SearchString;
			if (!string.IsNullOrEmpty(searchString))
			{
				AppArguments.Instance.SearchString = string.Empty;
				this._filterControl.ChangeFilterValue("PartName", searchString);
				AppArguments.Instance.SearchString = string.Empty;
			}
		}

		private void Shift_KeyDown(object sender, KeyEventArgs e)
		{
			if (e.Key == Key.LeftShift || e.Key == Key.RightShift)
			{
				this._isShiftPressed = true;
				if (this._grid.SelectedItems.Count > 0)
				{
					this._firstSelectedIndex = this._grid.Items.IndexOf(this._grid.SelectedItems[0]);
					return;
				}
			}
			else if (e.Key == Key.LeftCtrl || e.Key == Key.RightCtrl)
			{
				this._isCtrlPressed = true;
			}
		}

		private void Shift_KeyUp(object sender, KeyEventArgs e)
		{
			if (e.Key == Key.LeftShift || e.Key == Key.RightShift)
			{
				this._isShiftPressed = false;
				return;
			}
			if (e.Key == Key.LeftCtrl || e.Key == Key.RightCtrl)
			{
				this._isCtrlPressed = false;
				return;
			}
			if (e.Key != Key.Delete)
			{
				if (e.Key == Key.Return)
				{
					this.OkButtonClick();
					return;
				}
				if (e.Key == Key.A && this._grid.SelectionMode == DataGridSelectionMode.Extended && this._isCtrlPressed)
				{
					this._selectedState = !this._selectedState;
					this.ChangeSelection(this._selectedState);
				}
			}
			else if (this._isCtrlPressed)
			{
				this.ChangeSelection(false);
				return;
			}
		}

		public void WriteErg0File()
		{
			List<CadPartInfo> cadPartInfos = new List<CadPartInfo>();
			if (this._grid.SelectionMode == DataGridSelectionMode.Extended)
			{
				List<VariantInfo> variantInfos = this.ArchiveContent.ToList<VariantInfo>().FindAll((VariantInfo x) => x.IsSelected);
				if (!EnumerableHelper.IsNullOrEmpty(variantInfos))
				{
					foreach (VariantInfo variantInfo in variantInfos)
					{
						cadPartInfos.Add(variantInfo);
					}
				}
			}
			else if (this._grid.SelectedItem is CadPartInfo)
			{
				cadPartInfos.Add((CadPartInfo)this._grid.SelectedItem);
			}
			(new Erg0Helper()).WriteCadPartsErg0(cadPartInfos);
		}
	}
}